AuthorizeForGuitarNode/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using AuthorizeForGuitarNode.Models.Articles;
using AuthorizeForGuitarNode.Models.WorkWithData;
using PagedList;
using PagedList.Mvc;
using AuthorizeForGuitarNode.Helpers;

namespace AuthorizeForGuitarNode.Controllers
{

    public class ArticlesController : Controller
    {
        List<Article> articleCollection;
        Article article;
        DataWorker dataWorker;
        Comment cmt;
        int currentPage, pageQuantityObjects = 8;// количество объектов на страницу;

        // GET: Home
        public ActionResult IndexArticles(int? page)
        {
            ArticlesContext ctxt = new ArticlesContext();
            currentPage = (page ?? 1);
            articleCollection = new List<Article>(ctxt.Articles);
            ctxt.Dispose();
            IEnumerable<Article> phonesPerPages = articleCollection.Skip((page ?? 1 - 1) * pageQuantityObjects).Take(pageQuantityObjects);
            PageInfo pageInfo = new PageInfo { PageNumber = page ?? 1, PageSize = pageQuantityObjects, TotalItems = articleCollection.Count };
            IndexViewModel ivm = new IndexViewModel { PageInfo = pageInfo, Articles = phonesPerPages };

            return View(ivm);
        }

        [HttpPost]
        public ActionResult ArticleViewer(string id)
        {
            if (id != null)
            {
                using (ArticlesContext ctxt = new ArticlesContext())
                {
                    try
                    {
                        article = new Article();
                        article = ctxt.Articles.Where(c => c.ArticleId == id).FirstOrDefault();
                        //View count
                        article.Viewed += 1;
                        Session["currentArticle"] = article.ArticleId;
                        ctxt.SaveChanges();

                    }
                    catch (Exception ex)
                    {
                        return Content(ex.Message);
                    }
                }
            }
            else
                return Content("Something wrong!!!");

            return View(article);
        }

        //Добавляем комментарий
        [HttpPost]
        [Authorize]
        public ActionResult ContentComment(string commentContent)
        {
            dataWorker = new DataWorker();
            string articleId = Session["currentArticle"].ToString();

            if (commentContent != null && commentContent != string.Empty)
               cmt = dataWorker.AddNewComment(commentContent, articleId);
            return View(cmt);
        }

        public ActionResult CommentViewer()
        {
            dataWorker = new DataWorker();
            string articleId = Session["currentArticle"].ToString();

            return View(dataWorker.GetAllComments(articleId));
        }
    }
}

AuthorizeForGuitarNode/Controllers/ChordsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AuthorizeForGuitarNode.Controllers
{
    public class ChordsController : Controller
    {
        // GET: Chords
        public ActionResult IndexChords()
        {
            return View();
        }
    }
}

AuthorizeForGuitarNode/Controllers/GuitarFormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AuthorizeForGuitarNode.Controllers
{
    public class GuitarFormController : Controller
    {
        // GET: GuitarForm
        public ActionResult Decription(string value)
        {
            var obj = value;
            return View(obj);
        }
    }
}

AuthorizeForGuitarNode/Controllers/LessonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AuthorizeForGuitarNode.Controllers
{
    public class LessonsController : Controller
    {
        // GET: Lessons
        public ActionResult IndexLessons()
        {
            return View();
        }
    }
}

AuthorizeForGuitarNode/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/FontAwesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/Bubbles/bubbleSpeech.css" rel="stylesheet" />
    <link href="~/Content/Bubbles/squareMessage.css" rel="stylesheet" />
    <link href="~/Content/Bubbles/CloudComment.css" rel="stylesheet" />
    <link href="~/Content/MenuStyle/Menu.css" rel="stylesheet" />
    <link href="~/Content/ButtonTop.css" rel="stylesheet" />
    <link href="~/Content/MenuStyle/MenuFont.css" rel="stylesheet" />
    <link href="~/Content/Body/BodyBackground.css" rel="stylesheet" />
    <link href="~/Content/FixedButtons.css" rel="stylesheet" />

    @*GoogleFonts_____*@
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">

    @*________________*@

    <script src="~/Scripts/modernizr-2.6.2.js"></script>


    <style>
        body {
            font-family: 'Indie Flower', cursive;
        }
    </style>
</head>


<body>
    
    @*@*___________LeftMenuFixed*@
    <a class="fxdButton" style="width : 50px ; height : 50px ; padding-top : 10px;" href=@Url.Action("Decription", "GuitarForm", new { value = "Explorer"})><img src="~/Resources/SideIconGuitar/Explorer.png" /></a>
    <a class="fxdButton" style="width : 50px ; height : 50px ; padding-top : 60px;" href=@Url.Action("Decription", "GuitarForm", null)><img src="~/Resources/SideIconGuitar/FlyingV.png" /></a>
    <a class="fxdButton" style="width : 50px ; height : 50px ; padding-top : 110px" href=@Url.Action("Decription", "GuitarForm", null)><img src="~/Resources/SideIconGuitar/Jackson.png" /></a>
    <a class="fxdButton" style="width : 50px ; height : 50px ; padding-top : 160px" href=@Url.Action("Decription", "GuitarForm", null)><img src="~/Resources/SideIconGuitar/LesPaul.png" /></a>
    <a class="fxdButton" style="width : 50px ; height : 50px ; padding-top : 210px" href=@Url.Action("Decription", "GuitarForm", null)><img src="~/Resources/SideIconGuitar/Guild.png" /></a>
    <a class="fxdButton" style="width : 50px ; height : 50px ; padding-top : 260px" href=@Url.Action("Decription", "GuitarForm", null)><img src="~/Resources/SideIconGuitar/SantanaPRS.png" /></a>
    <a class="fxdButton" style="width : 50px ; height : 50px ; padding-top : 310px" href=@Url.Action("Decription", "GuitarForm", null)><img src="~/Resources/SideIconGuitar/Stratocaster.png" /></a>
    <a class="fxdButton" style="width : 50px ; height : 50px ; padding-top : 360px" href=@Url.Action("Decription", "GuitarForm", null)><img src="~/Resources/SideIconGuitar/Telecaster.png" /></a>
    <a class="fxdButton" style="width : 50px ; height : 50px ; padding-top : 410px" href=@Url.Action("Decription", "GuitarForm", null)><img src="~/Resources/SideIconGuitar/JacksonKingV.png" /></a>
    <a class="fxdButton" style="width : 50px ; height : 50px ; padding-top : 460px" href=@Url.Action("Decription", "GuitarForm", null)><img src="~/Resources/SideIconGuitar/DeanML.png" /></a>
    <a class="fxdButton" style="width : 50px ; height : 50px ; padding-top : 510px" href=@Url.Action("Decription", "GuitarForm", null)><img src="~/Resources/SideIconGuitar/Wasburn.png" /></a>
    <a class="fxdButton" style="width : 50px ; height : 50px ; padding-top : 560px" href=@Url.Action("Decription", "GuitarForm", null)><img src="~/Resources/SideIconGuitar/EVH FrankensteinReplica.png" /></a>
    <a class="fxdButton" style="width : 50px ; height : 50px ; padding-top : 610px" href=@Url.Action("Decription", "GuitarForm", null)><img src="~/Resources/SideIconGuitar/MichaelAngelo.png" /></a>
    <a class="fxdButton" style="width : 50px ; height : 50px ; padding-top : 660px" href=@Url.Action("Decription", "GuitarForm", null)><img src="~/Resources/SideIconGuitar/Rickenbacker.png" /></a>
    <a class="fxdButton" style="width : 50px ; height : 50px ; padding-top : 710px" href=@Url.Action("Decription", "GuitarForm", null)><img src="~/Resources/SideIconGuitar/SweetHeart.png" /></a>
    <a class="fxdButton" style="width : 50px ; height : 50px ; padding-top : 760px" href=@Url.Action("Decription", "GuitarForm", null)><img src="~/Resources/SideIconGuitar/BCRich.png" /></a>
    @*________________________*@*

    <div style="height : 50px"></div>

    <div style="width : 1000px ; position : absolute; top: 0; right: 0; bottom: 0; left: 0; margin: auto;">
        <nav>
            <ul>
                <li>
                    <img src="~/Resources/Icons/Jackson.png" />
                </li>
                <li>
                    @Html.ActionLink("Главная", "Index", "Home", new { area = "" }, new { @class = "menuFont my-class" })
                </li>

                <li>
                    @Html.ActionLink("Статьи", "IndexArticles", "Articles", new { area = "" }, new { @class = "menuFont my-class" })

                </li>
                <li>
                    @Html.ActionLink("Уроки", "IndexLessons", "Lessons", new { area = "" }, new { @class = "menuFont my-class" })
                    <ul style="z-index : 10">
                        <li>
                            @Html.ActionLink("Акукстика", "IndexLessons", "Lessons", new { area = "" }, new { @class = "menuFont my-class" })
                        </li>
                        <li>
                            @Html.ActionLink("Электруха", "IndexLessons", "Lessons", new { area = "" }, new { @class = "menuFont my-class" })
                        </li>
                    </ul>
                </li>
                <li>
                    @Html.ActionLink("Мат. Часть", "IndexStructure", "GuitarStructure", new { area = "" }, new { @class = "menuFont my-class" })
                    <ul style="z-index : 10">
                        <li>
                            @Html.ActionLink("Акукстика", "IndexLessons", "Lessons", new { area = "" }, new { @class = "menuFont my-class" })
                        </li>
                        <li>
                            @Html.ActionLink("Электруха", "IndexLessons", "Lessons", new { area = "" }, new { @class = "menuFont my-class" })
                        </li>
                    </ul>
                </li>
                <li>
                    @Html.ActionLink("Генератор аккордов", "IndexChords", "Chords", new { area = "" }, new { @class = "menuFont" })
                </li>
                <li>

                </li>
                <li>
                    <img src="~/Resources/Icons/AuthIco.png" style="width : 50px ; height : 50px" />
                </li>
                <li>
                    <img src="~/Resources/Icons/JacksonReflected.png" />
                </li>
            </ul>
        </nav>
    </div>


    @*_____________________________________Content_____________________________________________________________________________________________________________________________*@
    <div style="z-index : -1; height : 5000px; width : 1080px;  top: 0; right: 0; bottom: 0; left: 0; margin: auto;">
        <div class="col-md-1 col-sm-1 col-xs-1"></div>
        <div class="col-md-10 col-sm-10 col-xs-10" style="background-color : transparent">
            <p></p>

            <div class="row">
                <div class="col-md-2 col-sm-2 col-xs-2">
                    @RenderSection("RandomPhoto", false);
                </div>
                @*  Picture according ran phrase    <div class="col-md-2 col-sm-2 col-xs-2"><img src="~/Resources/Photo/JamesHetfield2012.jpg" height="200" width="200" style="padding : 0,0,0,0" /></div>*@
                <div class="col-md-10 col-sm-10 col-xs-10" style="background-color : transparent">
                    @RenderSection("RandomPhrase", false);
                    @*<div id="PhraseContainer" style="background-color : bisque ; height:200px ; padding-left : 20px; padding-right : 20px; padding-top : 20px;">
                            <p class="speech" style="line-height: 40px;">
                                <i id="RandomPhrase" style="font-size :small ; line-height: 50%">
                                    @TempData["randomContent"]
                                </i>
                            </p>

                            <br />
                            <p id="PhraseAuthor" style="margin-bottom : 0px ; font-size : initial">@TempData["randomAuthor"]</p>
                        </div>*@
                </div>
            </div>

            <p></p>

            <div class="row">
                <div class="col-md-9 col-sm-9 col-xs-9" style="background-color : darkgrey">
                    @RenderBody()
                </div>
                <div class="col-md-3 col-sm-3 col-xs-3" style="background-color : brown">
                    @RenderSection("Authorization", false)
                    @RenderSection("Voting", false)
                    <h3>Так же может быть интересно : </h3>
                    <p>
                        Класс row задает расположение отдельных блоков в виде одной строки. Строка в Bootstrap может иметь до 12 столбцов. Строк может быть сколько угодно, но в данном случае у нас одна строка.

                        Для создания отдельного столбца строки используется класс col-md-4. col, как ясно из названия, обозначает столбец.

                        Дальше идет md - идентификатор устройства. Как мы увидели в прошлой теме, bootstrap делит все устройства условно на четыре группы в зависимости от ширины экрана. md, в частности, соотносится со средними устройствами (то есть которые имеют ширину от 992 пикселя и выше). А число 4 указывает, сколько условных единиц в строке будет занимать данный блок. Таким образом, получается, что класс col-md-4 означает, что данный блок будет занимать 4 условных единицы из 12 в строке, то есть треть ширины экрана устройства с экраном шириной от 992 пикселей.

                        И поскольку у нас есть четыре группы, то для каждой группы имеются свои классы. Например, для очень маленьких устройств с экраном меньше 768 пикселей (то есть мобильных телефонов), подобный класс мог бы быть таким col-xs-4.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-1 col-sm-1 col-xs-1"></div>
    </div>


    @*______________________________________________________________________End_Content_______________________________________________________________________________________*@

    @*<button id="top"><img src="~/Resources/Photo/FlyingVButtonTop.png" height="80" width="40" /></button>*@

    <img id="top" class="megaweb" src="~/Resources/Photo/FlyingVButtonTopWhite.png" height="80" width="40" onmouseover="TransparentChanger()" onmouseout="SetTransparent()" />

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    <script>
        @*//______Poll from client to server_____________________________________________________________
        var i = 0;
        var intervalId = window.setInterval(function () {
            // send AJAX requests every 'x' seconds to check for updates
            $.getJSON('@Url.Action("poll")', function (dataFromServer) {
                document.getElementById('RandomPhrase').innerHTML = dataFromServer.Content;
                document.getElementById('PhraseAuthor').innerHTML = dataFromServer.PhraseAuthor;
            });
        }, 4000);
        //_____________________________________________________________________________________________*@

        //______GoUpButton_____________________________________________________________________________
        var pointVisible = 150; // В каком положении полосы прокрутки начинать показ кнопки "Наверх"
        var delay = 1000; // Задержка прокрутки
        $(document).ready(function () {
            $(window).scroll(function () { // При прокрутке попадаем в эту функцию
                /* В зависимости от положения полосы прокрукти и значения pointVisible, скрываем или открываем кнопку "Наверх" */
                if ($(this).scrollTop() > pointVisible) $('#top').fadeIn();
                else $('#top').fadeOut();
            });
            $('#top').click(function () { // При клике по кнопке "Наверх" попадаем в эту функцию
                /* Плавная прокрутка наверх */
                $('body, html').animate({
                    scrollTop: 0
                }, delay);
            });
        });
        //_____________________________________________________________________________________________

        //______TransparentChange______________________________________________________________________
        $(document).ready(function () {
            $('#top').each(function () {
                $(this).animate({ opacity: '0.3' }, 1);
                $(this).mouseover(function () {
                    $(this).stop().animate({ opacity: '1.0' }, 600);
                });
                $(this).mouseout(function () { $(this).stop().animate({ opacity: '0.3' }, 300); });
            });
        });
        //_____________________________________________________________________________________
    </script>


</body>
</html>